### ISSUE TITLE
OpenIG cannot load js files with docker version

### ISSUE THREAD

**Issue by dairoca90** [OpenIdentityPlatform/OpenIG#15]
So after i install de docker latest version of OpenIG many .js files for the UI are not loading correctly and affect some functionality of the platform, when i try to see my saved routes in the UI nothing happens.

![image](https://user-images.githubusercontent.com/38822740/115981467-a68f1780-a559-11eb-9dbe-1481c8fbcce1.png)

![image](https://user-images.githubusercontent.com/38822740/115981479-b9a1e780-a559-11eb-8e76-c1a05d291c86.png)

**Comment by maximthomas** [comment]
resolved in the latest sources
