### ISSUE TITLE
OpenIG dont create log folder in docker container

### ISSUE THREAD

**Issue by dairoca90** [OpenIdentityPlatform/OpenIG#16]
After i create a route in development mode or production mode openig just creates the config folder but not the log folder even if i set de capture option correctly.

**Comment by maximthomas** [comment]
@dairoca90   add system property to your docker run command
```
-Dlogback.configurationFile=/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/org/forgerock/openig/web/logback.xml
```
and try again
