### ISSUE TITLE
Unable to build UI

### ISSUE THREAD

**Issue by dairoca90** [OpenIdentityPlatform/OpenIG#38]
**Describe the bug**
When i try to build the ui with mvn clean install fails trying to get some dependencies

**Screenshots**
<img width="1408" alt="Captura de Pantalla 2022-07-13 a la(s) 21 31 12" src="https://user-images.githubusercontent.com/38822740/178885830-47604a44-3748-4b8e-9116-cac13741ad9c.png">

**Desktop :**
 - Device: mac
  - OS: Monterey 12.4

**Comment by maximthomas** [comment]
@dairoca90 check the latest sources
